networks:
  dev:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 8080:80
    networks:
      dev:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - web
    networks:
      dev: